{{- if and .Values.hazelcast.enabled (or .Values.hazelcast.configurationFiles .Values.hazelcast.yaml) (not .Values.hazelcast.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hazelcast.fullname" . }}-configuration
  labels:
    app.kubernetes.io/name: {{ template "hazelcast.name" . }}
    helm.sh/chart: {{ template "hazelcast.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    {{- range $key, $value := .Values.commonLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{- range $key, $val := .Values.hazelcast.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
  hazelcast.yaml: |-
{{ toYaml .Values.hazelcast.yaml | indent 4 }}
{{- end -}}
