name: Push Helm JET 4.3.z charts to the repo

on:
  push:
    branches:
      - 4.3.z
    paths:
      - "stable/hazelcast-jet*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: azure/setup-helm@v1
        with:
          version: 'v3.2.1'
        id: install

      - name: Package jet charts and add them into index.yaml
        run: |
          for CHART in ./stable/*jet*; do helm package ${CHART}; done
          aws s3 cp s3://hazelcast-charts/index.yaml .
          helm repo index --url=https://hazelcast-charts.s3.amazonaws.com --merge ./index.yaml .

      - name: Push jet charts and index.yaml to S3 bucket
        run: |
          for CHART_TGZ in *.tgz; do aws s3 cp ${CHART_TGZ} s3://hazelcast-charts; done
          aws s3 cp ./index.yaml s3://hazelcast-charts