name: Push Helm 3.12.z charts to the repo

on:
  push:
    branches: '3.12.z'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: azure/setup-helm@v1
        with:
          version: 'v3.2.1'
        id: install

      - name: Download existing Helm charts and index.yaml
        run: |
          mkdir tmp
          aws s3 sync s3://hazelcast-charts ./tmp

      - name: Package modified Helm charts and update index.yaml
        run: |
          for CHART in ./stable/*; do helm package ${CHART}; done
          cp *.tgz ./tmp/
          helm repo index --url=https://hazelcast-charts.s3.amazonaws.com ./tmp

      - name: Push charts to S3 bucket
        run: |
          aws s3 cp ./tmp/index.yaml s3://hazelcast-charts
          rm -rf ./tmp
          for CHART in *.tgz; do aws s3 cp ${CHART} s3://hazelcast-charts; done