name: Push Helm charts to the repo

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "stable/hazelcast/**"
      - "stable/hazelcast-enterprise/**"
      - "artifacthub-repo.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_HAZELCAST_OIDC_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: us-east-1

      - uses: azure/setup-helm@v4
        with:
          version: 'v3.2.1'
        id: install

      - name: Package charts and add them into index.yaml
        run: |
          helm package ./stable/hazelcast
          helm package ./stable/hazelcast-enterprise
          aws s3 cp s3://hazelcast-charts/index.yaml .
          helm repo index --url=https://hazelcast-charts.s3.amazonaws.com --merge ./index.yaml .

      - name: Push charts and index.yaml to S3 bucket
        run: |
          for CHART_TGZ in *.tgz; do aws s3 cp ${CHART_TGZ} s3://hazelcast-charts; done
          aws s3 cp ./index.yaml s3://hazelcast-charts

      - name: Push ArtifactHub metadata YAML to the S3 bucket
        run: |
          aws s3 cp ./artifacthub-repo.yml s3://hazelcast-charts
